[package]
name = "oxyde"
version = "0.0.2"
authors = ["DE SMET Enguerrand"]
edition = "2021"

[features]
glsl = ["dep:shaderc"]
icon = ["dep:image"]

[dependencies]
winit = "0.28.7"

log = "0.4"

wgpu = { version = "0.18", features = [ "spirv" ] }
pollster = "0.3"
bytemuck = { version = "1.13", features = [ "derive" ] }
anyhow = "1"

egui = "0.23.0"
egui_wgpu_backend = "0.27"
egui_winit_platform = "0.20"

spin_sleep = "1"

image = { version = "0.24", optional = true }
shaderc = { version = "0.8", optional = true }

nalgebra-glm = { version = "0.18", features = ["serde-serialize"] }